dist: bionic

sudo: false

language: php

services:
  - mysql
  - postgresql

php:
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - CORE_BRANCH=stable21
    - APP_NAME=facerecognition
  matrix:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite

before_install:
  # Installing pdlib (install dlib from repo and compile pdlib on top of it)
  - sudo sh -c 'echo "deb https://repo.delellis.com.ar bionic bionic" > /etc/apt/sources.list.d/20-pdlib.list'
  - wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - sudo apt update
  - sudo apt-get install libdlib-dev
  - wget https://github.com/goodspb/pdlib/archive/v1.0.2.tar.gz
  - tar -xzf v1.0.tar.gz
  - pushd pdlib-1.0
  - phpize
  - ./configure --enable-debug && make && sudo make install
  - echo "extension=pdlib.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - popd
  - sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
  - sudo apt-get install npm
  - sudo npm config set strict-ssl false
  - make
  - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh;
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../server;
  - ./occ app:enable $APP_NAME

before_script:
  - ./occ app:check-code $APP_NAME || true
  - cd apps/$APP_NAME

script:
  # Install models here is useless but they are a test of themselves.
  - ../../occ face:setup --model 3 || true
  - ../../occ face:setup --model 1
  - make test

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

after_failure:
  - cat ../../data/nextcloud.log
